CREATE TABLE IF NOT EXISTS mpa_ratings (
    mpa_id INT PRIMARY KEY,
    name VARCHAR(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS genres (
    genre_id INT PRIMARY KEY,
    name VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    login VARCHAR(255) NOT NULL UNIQUE,
    name VARCHAR(255),
    birthday DATE
);

CREATE TABLE IF NOT EXISTS films (
    film_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(200),
    release_date DATE,
    duration INT,
    mpa_id INT REFERENCES mpa_ratings (mpa_id)
);

CREATE TABLE IF NOT EXISTS film_genres (
    film_id BIGINT NOT NULL REFERENCES films (film_id) ON DELETE CASCADE,
    genre_id INT NOT NULL REFERENCES genres (genre_id),
    PRIMARY KEY (film_id, genre_id)
);

CREATE TABLE IF NOT EXISTS likes (
    film_id BIGINT NOT NULL REFERENCES films (film_id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES users (user_id) ON DELETE CASCADE,
    PRIMARY KEY (film_id, user_id)
);

-- Справочник статусов дружбы. Сейчас используется единственное значение
-- CONFIRMED, так как заявка в друзья применяется сразу и без подтверждения
-- (дружба односторонняя — см. friendships). Таблица оставлена по ER-схеме
-- для расширяемости (например, REQUESTED, если в будущем понадобится
-- подтверждение дружбы).
CREATE TABLE IF NOT EXISTS friendship_status (
    status_id INT PRIMARY KEY,
    name VARCHAR(20) NOT NULL
);

-- Дружба односторонняя: строка (user_id, friend_id) означает,
-- что user_id добавил friend_id к себе в друзья. Взаимность не создаётся автоматически.
CREATE TABLE IF NOT EXISTS friendships (
    user_id BIGINT NOT NULL REFERENCES users (user_id) ON DELETE CASCADE,
    friend_id BIGINT NOT NULL REFERENCES users (user_id) ON DELETE CASCADE,
    status_id INT NOT NULL REFERENCES friendship_status (status_id),
    PRIMARY KEY (user_id, friend_id)
);

CREATE INDEX IF NOT EXISTS idx_film_genres_genre_id ON film_genres (genre_id);
CREATE INDEX IF NOT EXISTS idx_likes_user_id ON likes (user_id);
CREATE INDEX IF NOT EXISTS idx_friendships_friend_id ON friendships (friend_id);
CREATE INDEX IF NOT EXISTS idx_friendships_status_id ON friendships (status_id);
